[package]
name = "boilaDB"
version = "0.2.0"
entry = "tools/serve.baga"

[dependencies]
std = { path = "../../std" }
rocksbaga = { path = "../rocksbaga" }
httpdbaga = { path = "../httpdbaga" }
metbaga = { path = "../metbaga" }
bagadecimal = { path = "../bagadecimal" }
csvbaga = { path = "../csvbaga" }
pgbaga = { path = "../pgbaga" }
raftbaga = { path = "../raftbaga" }
